// Public booking creation: one transaction, server-computed prices/durations/timestamps,
// database exclusion constraint as the final guard against double booking.
// Lifecycle and rules: docs/BOOKING-BUSINESS-LOGIC.md §8–§9.

import type { BookingCreatedResponse, ParsedBookingRequest } from "@autowascenter/shared";
import type { Database } from "../db/index.ts";
import { bookings, bookingServices } from "../db/schema/index.ts";
import { AppError } from "../errors/app-error.ts";
import { timeToMinutes } from "../lib/business-time.ts";
import {
  futureStarts,
  isOccupied,
  loadOccupancy,
  loadScheduleSettings,
} from "./availability.service.ts";
import {
  assertHasMainService,
  calculateLocationFeeCents,
  calculatePricing,
  centsToEuros,
  resolveSelection,
  toPricingContract,
  type PricedLine,
  type PricingCents,
} from "./pricing.service.ts";
import { candidateStarts, planJob, type PlannedJob } from "./schedule.ts";

const EXCLUSION_VIOLATION = "23P01";

export const slotUnavailable = () =>
  new AppError(409, "BOOKING_SLOT_UNAVAILABLE", "The chosen time slot is no longer available.");

/** True when the error (or a wrapped cause) is the bookings overlap exclusion violation. */
export function isOverlapViolation(error: unknown): boolean {
  for (let e = error, depth = 0; e && depth < 5; e = (e as { cause?: unknown }).cause, depth++) {
    if ((e as { code?: unknown }).code === EXCLUSION_VIOLATION) return true;
  }
  return false;
}

/** Everything needed to insert a booking; all values are server-computed except customer data. */
export interface BookingDraft {
  request: ParsedBookingRequest;
  lines: PricedLine[];
  totalDurationMinutes: number;
  pricing: PricingCents;
  job: PlannedJob;
  location: {
    onLocation: boolean;
    locationInSintNiklaas: boolean | null;
    locationAddress: string | null;
  };
}

const emptyToNull = (value: string | undefined) => (value ? value : null);

/**
 * Inserts the booking and its booking_services snapshot rows. Must run inside a transaction.
 * An overlap caught by the exclusion constraint (a concurrent booking committed after our
 * check) is reported as 409 BOOKING_SLOT_UNAVAILABLE, never as a database error.
 */
export async function insertBooking(tx: Database, draft: BookingDraft): Promise<string> {
  const { request: r, lines, job, pricing, location } = draft;
  try {
    const [row] = await tx
      .insert(bookings)
      .values({
        customerName: r.customer_name,
        customerEmail: r.customer_email,
        customerPhone: r.customer_phone,
        companyName: emptyToNull(r.company_name),
        vatNumber: emptyToNull(r.vat_number),
        notes: emptyToNull(r.notes),
        vehicleTypeId: r.vehicle_type_id,
        vehicleBrand: r.vehicle_brand,
        vehicleModel: r.vehicle_model,
        // Legacy columns, filled exactly like routes/reservatie.tsx so the admin UI keeps working.
        vehicleInfo: `${r.vehicle_brand} ${r.vehicle_model}`,
        serviceId: lines[0]?.serviceId ?? null,
        serviceTitle: lines.map((l) => l.title).join(", "),
        preferredDate: r.preferred_date,
        preferredTime: r.preferred_time,
        startAt: job.startAt,
        endAt: job.endAt,
        totalDurationMinutes: draft.totalDurationMinutes,
        totalPrice: (pricing.totalExclVat / 100).toFixed(2),
        locationFee: (pricing.locationFee / 100).toFixed(2),
        onLocation: location.onLocation,
        locationInSintNiklaas: location.locationInSintNiklaas,
        locationAddress: location.locationAddress,
        // Server-controlled: a public booking always starts as 'nieuw'.
        // cancel_token is generated by the database default (gen_random_uuid()).
        status: "nieuw",
      })
      .returning({ id: bookings.id });

    const bookingId = row!.id;
    await tx.insert(bookingServices).values(
      lines.map((line) => ({
        bookingId,
        serviceId: line.serviceId,
        serviceTitle: line.title,
        price: (line.priceCents / 100).toFixed(2),
        durationMinutes: line.durationMinutes,
      })),
    );
    return bookingId;
  } catch (error) {
    if (isOverlapViolation(error)) throw slotUnavailable();
    throw error;
  }
}

/**
 * Validates, prices and stores a public booking atomically. Every step runs in one
 * transaction: any error rolls back everything, so no half booking can remain.
 */
export async function createBooking(
  db: Database,
  request: ParsedBookingRequest,
  now: Date,
): Promise<BookingCreatedResponse["data"]> {
  const draft = await db.transaction(async (tx) => {
    const t = tx as unknown as Database;

    // 1-3. Services for the vehicle type, price and duration (from the database only).
    const { lines, totalDurationMinutes } = await resolveSelection(
      t,
      request.vehicle_type_id,
      request.service_ids,
    );
    assertHasMainService(lines);

    const location = {
      onLocation: request.on_location,
      locationInSintNiklaas: request.on_location ? Boolean(request.location_in_sint_niklaas) : null,
      locationAddress:
        request.on_location && !request.location_in_sint_niklaas
          ? emptyToNull(request.location_address)
          : null,
    };
    const pricing = calculatePricing(lines, calculateLocationFeeCents(location));

    // 4. Opening hours, slot grid, "not in the past", start_at/end_at.
    const settings = await loadScheduleSettings(t);
    const startMinutes = timeToMinutes(request.preferred_time);
    const validStarts = candidateStarts(totalDurationMinutes, settings);
    if (!validStarts.includes(startMinutes)) {
      throw new AppError(
        422,
        "BOOKING_OUTSIDE_OPENING_HOURS",
        "The chosen time is not an available start time within opening hours.",
      );
    }
    if (futureStarts(request.preferred_date, [startMinutes], now).length === 0) {
      throw new AppError(422, "BOOKING_IN_PAST", "The chosen date and time are in the past.");
    }
    const job = planJob(request.preferred_date, startMinutes, totalDurationMinutes, settings);
    if (!job) {
      throw new AppError(
        422,
        "BOOKING_OUTSIDE_OPENING_HOURS",
        "The chosen time does not exist in local time.",
      );
    }

    // 5. Existing bookings and blocked periods (friendly pre-check; the constraint is final).
    const occupancy = await loadOccupancy(
      t,
      request.preferred_date,
      totalDurationMinutes,
      settings,
    );
    if (isOccupied(job, occupancy)) throw slotUnavailable();

    const result: BookingDraft = {
      request,
      lines,
      totalDurationMinutes,
      pricing,
      job,
      location,
    };
    // 6-7. Insert booking + snapshots; 8. commit when the callback returns.
    const id = await insertBooking(t, result);
    return { ...result, id };
  });

  return {
    id: draft.id,
    status: "nieuw",
    preferred_date: request.preferred_date,
    preferred_time: request.preferred_time,
    start_at: draft.job.startAt.toISOString(),
    end_at: draft.job.endAt.toISOString(),
    pickup_date: draft.job.pickupDate,
    pickup_time: draft.job.pickupTime,
    total_duration_minutes: draft.totalDurationMinutes,
    services: draft.lines.map((l) => ({
      service_id: l.serviceId,
      title: l.title,
      kind: l.kind,
      price: centsToEuros(l.priceCents),
      duration_minutes: l.durationMinutes,
    })),
    pricing: toPricingContract(draft.pricing),
  };
}
